services:
  database:
    image: postgres:18
    container_name: snoopdoc-postgres
    environment:
      POSTGRES_USER: root_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: snoopdoc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
  
  redis:
    image: redis:8-alpine
    container_name: snoopdoc-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data: