
CREATE ROLE app_user WITH
    LOGIN
    PASSWORD 'postgres'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT;

GRANT CONNECT ON DATABASE snoopdoc TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE root_user IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE root_user IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;